name: Release-branch-creation

on:
  workflow_dispatch:
    inputs:
      current_release:
        description: "Current Release version"
        type: string
        required: true
      previous_release:
        description: "Previous Release vserion"
        type: string
        required: true
jobs:
  release_details:
    runs-on: ubuntu-latest

    steps:
      - name: Branch_details
        run: |
          echo "Current_release version is: ${{inputs.current_release}}
          echo "Previous_release version is: ${{inputs.previous_release}}
