name: Release-branch-creation

on:
  workflow_dispatch:
    inputs:
      release_branch:
        description: "Release Branch"
        type: string
        required: true
      current_release:
        description: "Current Release version"
        type: string
        required: true
      previous_release:
        description: "Previous Release vserion"
        type: string
        required: true
jobs:
  modify-release-files:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write
      
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.release_branch }}
          fetch-depth: 0

      - name: Create feature branch
        run: |
          FEATURE_BRANCH="feature/file-modification-${GITHUB_RUN_NUMBER}"
          echo "FEATURE_BRANCH=$FEATURE_BRANCH" >> "$GITHUB_ENV"
          git checkout -b "$FEATURE_BRANCH"

      - name: Run modification script
        env:
          PREVIOUS_RELEASE: ${{ inputs.previous_release }}
          CURRENT_RELEASE: ${{ inputs.current_release }}
        run: |
          chmod +x ./scripts/modify_files.sh
          ./scripts/modify_files.sh "$PREVIOUS_RELEASE" "$CURRENT_RELEASE"

      - name: Show changes
        run: |
          echo "Files changes:" git -status --short
          echo "Change Summary:" gitdiff -stat

      - name: Commit Changes
        run: |
          if git diff --quiet; then
            echo "No changes detected"
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "modify release files with current version"
      
      - name: Push feature branch
        run: |
          git push origin "$FEATURE_BRANCH"

      - name: Create pull request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create --base "${{ inputs.release_branch }}" --head "$FEATURE_BRANCH" --title "Release File Modification - $FEATURE_BRANCH" --body "Automated using modify-files.sh"
      
